services:
  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - --config.file=/etc/prometheus.yml
      - --enable-feature=otlp-write-receiver
      - --web.enable-remote-write-receiver
    volumes:
      - ./volumes/etc/prometheus.yml:/etc/prometheus.yml
