include:
  - ../common/network.yml

x-defaults: &defaults
  image: apache/kafka:3.7.0
  volumes:
    - ./volumes/etc/kafka/secrets:/etc/kafka/secrets
    - ./volumes/mnt/shared/config:/mnt/shared/config
  environment: &defaults-environment
    CLUSTER_ID: "kafka-local"
    KAFKA_PROCESS_ROLES: 'broker,controller'
    KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:29091,2@kafka-2:29092,3@kafka-3:29093"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'

services:
  kafka-1:
    <<: *defaults
    container_name: kafka-1
    ports: ["9091:9091"]
    environment:
      <<: *defaults-environment
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: "PLAINTEXT://:19091,CONTROLLER://:29091,EXTERNAL://:9091"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-1:19091,EXTERNAL://localhost:9091"

  kafka-2:
    <<: *defaults
    container_name: kafka-2
    ports: ["9092:9092"]
    environment:
      <<: *defaults-environment
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: "PLAINTEXT://:19092,CONTROLLER://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-2:19092,EXTERNAL://localhost:9092"

  kafka-3:
    <<: *defaults
    container_name: kafka-3
    ports: ["9093:9093"]
    environment:
      <<: *defaults-environment
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: "PLAINTEXT://:19093,CONTROLLER://:29093,EXTERNAL://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-3:19093,EXTERNAL://localhost:9093"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on: [kafka-1, kafka-2, kafka-3]
    ports: ["9090:8080"]
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:19091,kafka-2:19092,kafka-3:19093
